import React,{useEffect,useState} from 'react';import axios from 'axios';
const css={card:{background:'#101010',border:'1px solid #292929',borderRadius:8,padding:20},input:{width:'100%',boxSizing:'border-box',padding:10,background:'#080808',border:'1px solid #333',color:'#fff',borderRadius:5},btn:{padding:'9px 14px',background:'#ff5500',border:0,color:'#fff',borderRadius:5,fontWeight:700,cursor:'pointer'},muted:{color:'#999'}};
const statuses=['Reported','Investigating','Repair Scheduled','In Repair','Fixed','Returned','Cancelled'];
export default function AssetIssues({apiUrl,token,assets=[],users=[],isAdmin=false}){const[rows,setRows]=useState([]),[form,setForm]=useState({asset_id:'',title:'',description:'',priority:'Normal',assigned_user_id:''}),[filter,setFilter]=useState('All'),[error,setError]=useState('');const headers={Authorization:`Bearer ${token}`};
 const load=async()=>{try{const r=await axios.get(`${apiUrl}/issues`,{headers});setRows(r.data||[])}catch(e){setError(e.response?.data?.detail||'Unable to load issues.')}};useEffect(()=>{load()},[token]);
 const create=async e=>{e.preventDefault();try{await axios.post(`${apiUrl}/issues`,{...form,asset_id:Number(form.asset_id),assigned_user_id:form.assigned_user_id?Number(form.assigned_user_id):null},{headers});setForm({asset_id:'',title:'',description:'',priority:'Normal',assigned_user_id:''});setError('');load()}catch(e){setError(e.response?.data?.detail||'Unable to report issue.')}};
 const update=async(id,data)=>{try{await axios.put(`${apiUrl}/issues/${id}`,data,{headers});load()}catch(e){setError(e.response?.data?.detail||'Unable to update issue.')}};
 const shown=filter==='All'?rows:rows.filter(r=>r.status===filter);
 return <div><h1 style={{color:'#ff5500'}}>Asset Issues & Faults</h1><p style={css.muted}>Report, triage, repair and close asset faults.</p>{error&&<div style={{...css.card,color:'#ff9b9b',marginBottom:15}}>{error}</div>}
 {!isAdmin&&<form onSubmit={create} style={{...css.card,marginBottom:20}}><h3>Report a fault</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><select required style={css.input} value={form.asset_id} onChange={e=>setForm({...form,asset_id:e.target.value})}><option value=''>Select your asset</option>{assets.filter(a=>a.assigned_user_id).map(a=><option key={a.id} value={a.id}>{a.asset_tag} — {a.name}</option>)}</select><select style={css.input} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['Low','Normal','High','Critical'].map(x=><option key={x}>{x}</option>)}</select><input required style={css.input} placeholder='Issue title' value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required style={css.input} placeholder='Describe the fault' value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><button style={{...css.btn,marginTop:12}}>Report Fault</button></form>}
 {isAdmin&&<div style={{...css.card,marginBottom:20}}><strong>Filter:</strong> <select style={{...css.input,width:220,display:'inline-block',marginLeft:10}} value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></div>}
 <div style={css.card}>{shown.map(r=><div key={r.id} style={{padding:'15px 0',borderBottom:'1px solid #222'}}><div style={{display:'flex',justifyContent:'space-between',gap:15}}><div><strong style={{color:'#ff5500'}}>{r.asset_tag}</strong> — {r.title}<div style={css.muted}>{r.description}</div><div style={{fontSize:12,color:'#777'}}>Reported by {r.reported_by||'—'} · {new Date(r.created_at).toLocaleString('en-GB')}</div></div><div style={{textAlign:'right'}}><div>{r.priority} · {r.status}</div>{isAdmin&&<select style={{...css.input,width:180,marginTop:8}} value={r.status} onChange={e=>update(r.id,{status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select>}</div></div>{isAdmin&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:10}}><select style={css.input} value={r.assigned_user_id||''} onChange={e=>update(r.id,{assigned_user_id:e.target.value?Number(e.target.value):null})}><option value=''>Unassigned</option>{users.filter(u=>u.is_active).map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select><input style={css.input} placeholder='Resolution / work completed' defaultValue={r.resolution||''} onBlur={e=>update(r.id,{resolution:e.target.value})}/></div>}</div>)}{!shown.length&&<p style={css.muted}>No issues found.</p>}</div></div>}
