import React, { useEffect, useState } from 'react';

const card={background:'#111827',border:'1px solid #263244',borderRadius:12,padding:18};
const input={width:'100%',boxSizing:'border-box',padding:10,borderRadius:8,border:'1px solid #334155',background:'#0b1220',color:'#fff',marginTop:6};
const emptyDoc={asset_id:'',title:'',document_type:'Warranty',reference:'',issued_date:'',expiry_date:'',document_url:'',notes:''};
const emptyCompliance={asset_id:'',compliance_type:'Inspection',status:'Required',due_date:'',completed_date:'',reference:'',notes:''};

export default function ComplianceDocuments({apiUrl,token,assets=[]}){
  const [summary,setSummary]=useState(null),[docs,setDocs]=useState([]),[records,setRecords]=useState([]);
  const [doc,setDoc]=useState(emptyDoc),[compliance,setCompliance]=useState(emptyCompliance);
  const [message,setMessage]=useState(''),[error,setError]=useState(''),[filter,setFilter]=useState('');
  const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
  const load=async()=>{try{const [s,d,c]=await Promise.all(['summary','documents','compliance'].map(x=>fetch(`${apiUrl}/admin/${x==='summary'?'compliance/summary':x}`,{headers})));if(!s.ok||!d.ok||!c.ok)throw new Error('Unable to load compliance data');setSummary(await s.json());setDocs(await d.json());setRecords(await c.json());}catch(e){setError(e.message)}};
  useEffect(()=>{load()},[]);
  const clear=()=>{setMessage('');setError('')};
  const submit=async(e,type)=>{e.preventDefault();clear();const state=type==='doc'?doc:compliance;const path=type==='doc'?'documents':'compliance';const payload={...state,asset_id:Number(state.asset_id)};for(const k of ['issued_date','expiry_date','due_date','completed_date'])if(payload[k])payload[k]=new Date(payload[k]).toISOString();else if(k in payload)payload[k]=null;const r=await fetch(`${apiUrl}/admin/${path}`,{method:'POST',headers,body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)return setError(d.detail||'Could not save record');setMessage(type==='doc'?'Document added':'Compliance record added');type==='doc'?setDoc(emptyDoc):setCompliance(emptyCompliance);load()};
  const remove=async(path,id,label)=>{if(!window.confirm(`Delete this ${label}?`))return;clear();const r=await fetch(`${apiUrl}/admin/${path}/${id}`,{method:'DELETE',headers});const d=await r.json();if(!r.ok)return setError(d.detail||'Could not delete');setMessage(`${label} deleted`);load()};
  const visibleDocs=docs.filter(x=>!filter||`${x.asset_tag} ${x.asset_name} ${x.title} ${x.document_type}`.toLowerCase().includes(filter.toLowerCase()));
  const visibleRecords=records.filter(x=>!filter||`${x.asset_tag} ${x.asset_name} ${x.compliance_type} ${x.status}`.toLowerCase().includes(filter.toLowerCase()));
  const assetName=id=>{const a=assets.find(x=>x.id===Number(id));return a?a.asset_tag+' — '+a.name:'Select asset'};
  return <div style={{maxWidth:1250,margin:'0 auto',color:'#e5e7eb'}}><h1>Compliance & Documents</h1><p style={{color:'#94a3b8'}}>Keep asset certificates, warranties, inspections and compliance deadlines in one place.</p>
    {error&&<div style={{...card,borderColor:'#7f1d1d',marginBottom:16}}>{error}</div>}{message&&<div style={{...card,borderColor:'#14532d',marginBottom:16}}>{message}</div>}
    {summary&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:12,marginBottom:20}}>{[['Documents',summary.documents],['Expired docs',summary.expired_documents],['Docs due 30d',summary.documents_expiring_soon],['Compliance',summary.compliance_records],['Overdue',summary.overdue_compliance],['Due 30d',summary.compliance_due_soon]].map(([k,v])=><div key={k} style={card}><div style={{color:'#94a3b8',fontSize:13}}>{k}</div><div style={{fontSize:25,fontWeight:700,marginTop:5}}>{v}</div></div>)}</div>}
    <input placeholder="Search asset, document or compliance type..." style={{...input,marginBottom:18}} value={filter} onChange={e=>setFilter(e.target.value)}/>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(340px,1fr))',gap:18}}>
      <form onSubmit={e=>submit(e,'doc')} style={card}><h2>Add Document</h2><label>Asset<select required style={input} value={doc.asset_id} onChange={e=>setDoc({...doc,asset_id:e.target.value})}><option value="">Select asset</option>{assets.map(a=><option key={a.id} value={a.id}>{a.asset_tag} — {a.name}</option>)}</select></label><label>Title<input required style={input} value={doc.title} onChange={e=>setDoc({...doc,title:e.target.value})}/></label><label>Type<select style={input} value={doc.document_type} onChange={e=>setDoc({...doc,document_type:e.target.value})}>{['Warranty','Certificate','Inspection','Invoice','Lease','Policy','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Reference<input style={input} value={doc.reference} onChange={e=>setDoc({...doc,reference:e.target.value})}/></label><label>Issued<input type="date" style={input} value={doc.issued_date} onChange={e=>setDoc({...doc,issued_date:e.target.value})}/></label><label>Expiry<input type="date" style={input} value={doc.expiry_date} onChange={e=>setDoc({...doc,expiry_date:e.target.value})}/></label><label>Document URL<input type="url" style={input} value={doc.document_url} onChange={e=>setDoc({...doc,document_url:e.target.value})}/></label><label>Notes<textarea style={input} value={doc.notes} onChange={e=>setDoc({...doc,notes:e.target.value})}/></label><button style={{marginTop:12,padding:'10px 16px',borderRadius:8,cursor:'pointer'}}>Add Document</button></form>
      <form onSubmit={e=>submit(e,'compliance')} style={card}><h2>Add Compliance Record</h2><label>Asset<select required style={input} value={compliance.asset_id} onChange={e=>setCompliance({...compliance,asset_id:e.target.value})}><option value="">Select asset</option>{assets.map(a=><option key={a.id} value={a.id}>{assetName(a.id)}</option>)}</select></label><label>Type<select style={input} value={compliance.compliance_type} onChange={e=>setCompliance({...compliance,compliance_type:e.target.value})}>{['Inspection','PAT Test','Electrical Safety','Fire Safety','Insurance','Roadworthiness','Data/Security','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select style={input} value={compliance.status} onChange={e=>setCompliance({...compliance,status:e.target.value})}>{['Required','Scheduled','Completed','Not Required'].map(x=><option key={x}>{x}</option>)}</select></label><label>Due date<input type="date" style={input} value={compliance.due_date} onChange={e=>setCompliance({...compliance,due_date:e.target.value})}/></label><label>Completed date<input type="date" style={input} value={compliance.completed_date} onChange={e=>setCompliance({...compliance,completed_date:e.target.value})}/></label><label>Reference<input style={input} value={compliance.reference} onChange={e=>setCompliance({...compliance,reference:e.target.value})}/></label><label>Notes<textarea style={input} value={compliance.notes} onChange={e=>setCompliance({...compliance,notes:e.target.value})}/></label><button style={{marginTop:12,padding:'10px 16px',borderRadius:8,cursor:'pointer'}}>Add Compliance</button></form>
    </div>
    <div style={{...card,marginTop:20}}><h2>Documents</h2>{visibleDocs.length===0?<p style={{color:'#94a3b8'}}>No documents found.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Asset','Title','Type','Reference','Expiry','Link','Action'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #334155'}}>{h}</th>)}</tr></thead><tbody>{visibleDocs.map(d=><tr key={d.id}><td style={{padding:10}}>{d.asset_tag}</td><td>{d.title}</td><td>{d.document_type}</td><td>{d.reference||'—'}</td><td>{d.expiry_date?new Date(d.expiry_date).toLocaleDateString():'—'}</td><td>{d.document_url?<a href={d.document_url} target="_blank" rel="noreferrer">Open</a>:'—'}</td><td><button onClick={()=>remove('documents',d.id,'document')}>Delete</button></td></tr>)}</tbody></table></div>}</div>
    <div style={{...card,marginTop:20}}><h2>Compliance</h2>{visibleRecords.length===0?<p style={{color:'#94a3b8'}}>No compliance records found.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Asset','Type','Status','Due','Completed','Reference','Action'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #334155'}}>{h}</th>)}</tr></thead><tbody>{visibleRecords.map(r=><tr key={r.id}><td style={{padding:10}}>{r.asset_tag}</td><td>{r.compliance_type}</td><td>{r.status}</td><td>{r.due_date?new Date(r.due_date).toLocaleDateString():'—'}</td><td>{r.completed_date?new Date(r.completed_date).toLocaleDateString():'—'}</td><td>{r.reference||'—'}</td><td><button onClick={()=>remove('compliance',r.id,'compliance record')}>Delete</button></td></tr>)}</tbody></table></div>}</div>
  </div>;
}
