import React, { useEffect, useState } from 'react';
import axios from 'axios';

export default function ExecutiveHub({ apiUrl, token }) {
  const [tab,setTab]=useState('finance');
  const [finance,setFinance]=useState(null); const [analytics,setAnalytics]=useState(null); const [security,setSecurity]=useState(null); const [health,setHealth]=useState(null);
  const [expenses,setExpenses]=useState([]); const [budgets,setBudgets]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const headers={Authorization:`Bearer ${token}`};
  const load=async()=>{setLoading(true);setError('');try{const [f,a,e,b]=await Promise.all([axios.get(`${apiUrl}/admin/finance/summary`,{headers}),axios.get(`${apiUrl}/admin/analytics/summary`,{headers}),axios.get(`${apiUrl}/admin/expenses`,{headers}),axios.get(`${apiUrl}/admin/budgets`,{headers})]);setFinance(f.data);setAnalytics(a.data);setExpenses(e.data);setBudgets(b.data);try{const [s,h]=await Promise.all([axios.get(`${apiUrl}/admin/security/summary`,{headers}),axios.get(`${apiUrl}/admin/system/health`,{headers})]);setSecurity(s.data);setHealth(h.data)}catch(_){} }catch(e){setError(e.response?.data?.detail||'Unable to load executive data')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const money=n=>`£${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const createExpense=async()=>{const description=window.prompt('Expense description');if(!description)return;const amount=Number(window.prompt('Amount (£)','0'));if(!Number.isFinite(amount)||amount<0)return alert('Invalid amount');await axios.post(`${apiUrl}/admin/expenses`,{description,amount,category:'Other'}, {headers});load()};
  const createBudget=async()=>{const name=window.prompt('Budget name');if(!name)return;const amount=Number(window.prompt('Budget amount (£)','0'));if(!Number.isFinite(amount)||amount<0)return alert('Invalid amount');await axios.post(`${apiUrl}/admin/budgets`,{name,amount,year:new Date().getFullYear(),category:'General'}, {headers});load()};
  if(loading)return <div style={box}>Loading executive centre…</div>;
  if(error)return <div style={box}><strong>Executive centre</strong><p>{error}</p></div>;
  return <div style={{display:'grid',gap:20}}>
    <div style={box}><h1 style={h1}>APEX Executive Centre</h1><p style={muted}>Finance, analytics and system oversight.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['finance','analytics','security'].map(x=><button key={x} onClick={()=>setTab(x)} style={tab===x?activeBtn:btn}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div></div>
    {tab==='finance'&&<><div style={grid}>{[['Monthly Spend',money(finance.month_spend)],['Year Spend',money(finance.year_spend)],['Month Budget',money(finance.month_budget)],['Year Budget',money(finance.year_budget)],['Month Remaining',money(finance.month_remaining)],['Year Remaining',money(finance.year_remaining)]].map(([a,b])=><div style={card} key={a}><div style={muted}>{a}</div><strong style={{fontSize:24}}>{b}</strong></div>)}</div><div style={box}><div style={row}><h2 style={h2}>Expenses</h2><button style={activeBtn} onClick={createExpense}>+ Add Expense</button></div><table style={table}><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Asset</th><th>Amount</th></tr></thead><tbody>{expenses.slice(0,15).map(e=><tr key={e.id}><td>{e.expense_date?new Date(e.expense_date).toLocaleDateString():'—'}</td><td>{e.description}</td><td>{e.category}</td><td>{e.asset_tag||'—'}</td><td>{money(e.amount)}</td></tr>)}</tbody></table></div><div style={box}><div style={row}><h2 style={h2}>Budgets</h2><button style={activeBtn} onClick={createBudget}>+ Add Budget</button></div><table style={table}><thead><tr><th>Name</th><th>Category</th><th>Period</th><th>Amount</th></tr></thead><tbody>{budgets.map(b=><tr key={b.id}><td>{b.name}</td><td>{b.category}</td><td>{b.year}{b.month?` / ${b.month}`:' / Annual'}</td><td>{money(b.amount)}</td></tr>)}</tbody></table></div></>}
    {tab==='analytics'&&<><div style={grid}>{[['Assets',analytics.assets],['Asset Value',money(analytics.asset_value)],['Users',analytics.users],['Active Users',analytics.active_users],['Maintenance Spend',money(analytics.maintenance_spend)],['Total Expenses',money(analytics.expense_spend)],['Open Issues',analytics.open_issues]].map(([a,b])=><div style={card} key={a}><div style={muted}>{a}</div><strong style={{fontSize:24}}>{b}</strong></div>)}</div><div style={two}><div style={box}><h2 style={h2}>By Location</h2><List data={analytics.by_location}/></div><div style={box}><h2 style={h2}>By Lifecycle</h2><List data={analytics.by_lifecycle}/></div><div style={box}><h2 style={h2}>By Health</h2><List data={analytics.by_health}/></div><div style={box}><h2 style={h2}>By Category</h2><List data={analytics.by_category}/></div></div><div style={box}><a href={`${apiUrl}/admin/analytics/export`} onClick={e=>{e.preventDefault();axios.get(`${apiUrl}/admin/analytics/export`,{headers,responseType:'blob'}).then(r=>{const u=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=u;a.download='apex-asset-report.csv';a.click();URL.revokeObjectURL(u)})}}>Export full asset CSV</a></div></>}
    {tab==='security'&&<><div style={grid}>{[['Users',security?.users],['Active',security?.active_users],['Inactive',security?.inactive_users],['Unverified',security?.unverified_users],['Stale Accounts',security?.stale_users],['DB Status',health?.status||'—']].map(([a,b])=><div style={card} key={a}><div style={muted}>{a}</div><strong style={{fontSize:24}}>{b}</strong></div>)}</div><div style={two}><div style={box}><h2 style={h2}>System Health</h2><pre style={{whiteSpace:'pre-wrap',fontSize:13}}>{JSON.stringify(health?.checks||{},null,2)}</pre></div><div style={box}><h2 style={h2}>Recent Admin Activity</h2>{(security?.recent_admin_actions||[]).map((x,i)=><div key={i} style={{padding:'10px 0',borderBottom:'1px solid #292929'}}><strong>{x.action} {x.resource_type}</strong><div style={muted}>{x.resource_name} · {x.email}</div></div>)}</div></div></>}
  </div>
}
function List({data}){return <>{Object.entries(data||{}).sort((a,b)=>b[1]-a[1]).map(([k,v])=><div key={k} style={row}><span>{k}</span><strong>{v}</strong></div>)}</>}
const box={background:'#101010',border:'1px solid #252525',borderRadius:12,padding:20,color:'#eee'};const card={...box,padding:18};const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12};const two={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:16};const row={display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'};const h1={margin:'0 0 6px'};const h2={margin:'0 0 15px',fontSize:20};const muted={color:'#999',fontSize:13};const btn={background:'#1b1b1b',color:'#ddd',border:'1px solid #333',padding:'9px 14px',borderRadius:7,cursor:'pointer'};const activeBtn={...btn,background:'#d6a94a',color:'#111',borderColor:'#d6a94a'};const table={width:'100%',borderCollapse:'collapse',fontSize:14};
