import React, { useEffect, useState } from 'react';

const card = { background:'#111827', border:'1px solid #263244', borderRadius:12, padding:18 };
const input = { width:'100%', boxSizing:'border-box', padding:10, borderRadius:8, border:'1px solid #334155', background:'#0b1220', color:'#fff', marginTop:6 };

export default function Procurement({ apiUrl, token }) {
  const [summary,setSummary]=useState(null); const [suppliers,setSuppliers]=useState([]); const [orders,setOrders]=useState([]);
  const [supplier,setSupplier]=useState({name:'',contact_name:'',email:'',phone:'',website:'',address:'',notes:''});
  const [order,setOrder]=useState({order_number:'',supplier_id:'',status:'Draft',expected_date:'',notes:'',items:[{description:'',quantity:1,unit_cost:0}]});
  const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
  const load=async()=>{try{const [a,b,c]=await Promise.all([fetch(`${apiUrl}/admin/procurement/summary`,{headers}),fetch(`${apiUrl}/admin/suppliers`,{headers}),fetch(`${apiUrl}/admin/purchase-orders`,{headers})]);if(!a.ok||!b.ok||!c.ok)throw new Error('Unable to load procurement data');setSummary(await a.json());setSuppliers(await b.json());setOrders(await c.json());}catch(e){setError(e.message)}};
  useEffect(()=>{load()},[]);
  const createSupplier=async e=>{e.preventDefault();setMessage('');setError('');const r=await fetch(`${apiUrl}/admin/suppliers`,{method:'POST',headers,body:JSON.stringify(supplier)});const d=await r.json();if(!r.ok)return setError(d.detail||'Could not create supplier');setSupplier({name:'',contact_name:'',email:'',phone:'',website:'',address:'',notes:''});setMessage('Supplier created');load();};
  const createOrder=async e=>{e.preventDefault();setMessage('');setError('');const payload={...order,supplier_id:Number(order.supplier_id),expected_date:order.expected_date?new Date(order.expected_date).toISOString():null,items:order.items.map(i=>({...i,quantity:Number(i.quantity),unit_cost:Number(i.unit_cost)}))};const r=await fetch(`${apiUrl}/admin/purchase-orders`,{method:'POST',headers,body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)return setError(d.detail||'Could not create purchase order');setMessage(`Purchase order ${d.order_number} created`);setOrder({order_number:'',supplier_id:'',status:'Draft',expected_date:'',notes:'',items:[{description:'',quantity:1,unit_cost:0}]});load();};
  return <div style={{maxWidth:1200,margin:'0 auto',color:'#e5e7eb'}}><h1>Procurement</h1><p style={{color:'#94a3b8'}}>Suppliers, purchase orders and incoming asset spend.</p>
    {error&&<div style={{...card,borderColor:'#7f1d1d',marginBottom:16}}>{error}</div>}{message&&<div style={{...card,borderColor:'#14532d',marginBottom:16}}>{message}</div>}
    {summary&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12,marginBottom:20}}>{[['Active Suppliers',summary.suppliers],['Orders',summary.orders],['Ordered',summary.ordered],['Partial',summary.partially_received],['Received',summary.received],['Open Value',`£${Number(summary.open_value).toFixed(2)}`]].map(x=><div style={card} key={x[0]}><div style={{color:'#94a3b8',fontSize:13}}>{x[0]}</div><div style={{fontSize:25,fontWeight:700,marginTop:5}}>{x[1]}</div></div>)}</div>}
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:18}}>
      <form onSubmit={createSupplier} style={card}><h2>Add Supplier</h2>{[['name','Supplier name'],['contact_name','Contact name'],['email','Email'],['phone','Phone'],['website','Website']].map(([k,l])=><label key={k} style={{display:'block',marginBottom:10}}>{l}<input required={k==='name'} style={input} value={supplier[k]} onChange={e=>setSupplier({...supplier,[k]:e.target.value})}/></label>)}<label>Notes<textarea style={input} value={supplier.notes} onChange={e=>setSupplier({...supplier,notes:e.target.value})}/></label><button style={{marginTop:12,padding:'10px 16px',borderRadius:8,cursor:'pointer'}}>Create Supplier</button></form>
      <form onSubmit={createOrder} style={card}><h2>New Purchase Order</h2><label>Order number<input required style={input} value={order.order_number} onChange={e=>setOrder({...order,order_number:e.target.value})}/></label><label>Supplier<select required style={input} value={order.supplier_id} onChange={e=>setOrder({...order,supplier_id:e.target.value})}><option value="">Select supplier</option>{suppliers.filter(s=>s.is_active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Expected date<input type="date" style={input} value={order.expected_date} onChange={e=>setOrder({...order,expected_date:e.target.value})}/></label><h3>Items</h3>{order.items.map((it,idx)=><div key={idx} style={{border:'1px solid #263244',padding:10,borderRadius:8,marginBottom:8}}><input placeholder="Description" required style={input} value={it.description} onChange={e=>{const items=[...order.items];items[idx].description=e.target.value;setOrder({...order,items})}}/><input type="number" min="1" style={input} value={it.quantity} onChange={e=>{const items=[...order.items];items[idx].quantity=e.target.value;setOrder({...order,items})}}/><input type="number" min="0" step="0.01" style={input} value={it.unit_cost} onChange={e=>{const items=[...order.items];items[idx].unit_cost=e.target.value;setOrder({...order,items})}}/></div>)}<button type="button" onClick={()=>setOrder({...order,items:[...order.items,{description:'',quantity:1,unit_cost:0}]})}>+ Add item</button><br/><button style={{marginTop:12,padding:'10px 16px',borderRadius:8,cursor:'pointer'}}>Create Purchase Order</button></form>
    </div>
    <div style={{...card,marginTop:20}}><h2>Purchase Orders</h2>{orders.length===0?<p style={{color:'#94a3b8'}}>No purchase orders yet.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Order','Supplier','Status','Value','Expected','Items'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #334155'}}>{h}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id}><td style={{padding:10}}>{o.order_number}</td><td>{o.supplier_name}</td><td>{o.status}</td><td>£{Number(o.total_value).toFixed(2)}</td><td>{o.expected_date?new Date(o.expected_date).toLocaleDateString():'—'}</td><td>{o.items.length}</td></tr>)}</tbody></table></div>}</div>
  </div>;
}
