import React, { useEffect, useState } from 'react';
import axios from 'axios';

const styles={card:{background:'#101010',border:'1px solid #292929',borderRadius:8,padding:20},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12},muted:{color:'#999'},input:{width:'100%',boxSizing:'border-box',padding:10,background:'#080808',border:'1px solid #333',color:'#fff',borderRadius:5},btn:{padding:'9px 14px',background:'#ff5500',border:0,color:'#fff',borderRadius:5,fontWeight:700,cursor:'pointer'}};
export default function StockManagement({apiUrl,token,assets=[],users=[],onRefresh}){
 const [summary,setSummary]=useState({}); const [selected,setSelected]=useState([]); const [userId,setUserId]=useState(''); const [location,setLocation]=useState('APEX HUB'); const [notes,setNotes]=useState(''); const [movements,setMovements]=useState([]); const [error,setError]=useState(''); const headers={Authorization:`Bearer ${token}`};
 const load=async()=>{try{const [s,m]=await Promise.all([axios.get(`${apiUrl}/stock/summary`,{headers}),axios.get(`${apiUrl}/stock/movements`,{headers})]);setSummary(s.data);setMovements(m.data||[])}catch(e){setError(e.response?.data?.detail||'Unable to load stock data.')}};
 useEffect(()=>{load()},[token]);
 const bulk=async()=>{if(!selected.length)return setError('Select at least one asset.');try{await axios.post(`${apiUrl}/assets/bulk-assign`,{asset_ids:selected,user_id:userId?Number(userId):null,location,notes},{headers});setSelected([]);setNotes('');setError('');await load();onRefresh?.()}catch(e){setError(e.response?.data?.detail||'Stock update failed.')}};
 return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:18}}><div><h1 style={{color:'#ff5500',marginBottom:5}}>Stock & Inventory</h1><span style={styles.muted}>Check assets in/out, transfer stock and review movement history.</span></div></div>
 {error&&<div style={{...styles.card,borderColor:'#7b2d2d',marginBottom:15,color:'#ff9b9b'}}>{error}</div>}
 <div style={{...styles.grid,marginBottom:20}}>{[['Total',summary.total],['In Stock',summary.in_stock],['Assigned',summary.assigned],['Maintenance',summary.in_maintenance],['Returned',summary.returned],['Replacement',summary.replacement_required],['Retired',summary.retired]].map(x=><div key={x[0]} style={styles.card}><div style={styles.muted}>{x[0]}</div><strong style={{fontSize:28,color:'#ff5500'}}>{x[1]??0}</strong></div>)}</div>
 <div style={{...styles.card,marginBottom:20}}><h3>Bulk stock movement</h3><p style={styles.muted}>Select assets below, then assign them to an employee or return them to a location.</p><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr',gap:12,marginBottom:12}}><select style={styles.input} value={userId} onChange={e=>setUserId(e.target.value)}><option value=''>Return to stock / no employee</option>{users.filter(u=>u.is_active).map(u=><option key={u.id} value={u.id}>{u.full_name} — {u.email}</option>)}</select><input style={styles.input} value={location} onChange={e=>setLocation(e.target.value)} placeholder='Location'/><input style={styles.input} value={notes} onChange={e=>setNotes(e.target.value)} placeholder='Notes'/></div><button style={styles.btn} onClick={bulk}>Apply to {selected.length} selected</button></div>
 <div style={styles.card}><h3>Assets</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['','APEX ID','Asset','Location','Lifecycle','Assigned To'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #333',color:'#999'}}>{h}</th>)}</tr></thead><tbody>{assets.map(a=><tr key={a.id}><td style={{padding:10}}><input type='checkbox' checked={selected.includes(a.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,a.id]:s.filter(id=>id!==a.id))}/></td><td style={{padding:10,color:'#ff5500'}}>{a.asset_tag}</td><td style={{padding:10}}>{a.name}</td><td style={{padding:10}}>{a.location}</td><td style={{padding:10}}>{a.lifecycle_status}</td><td style={{padding:10}}>{a.assigned_user?.full_name||'Unassigned'}</td></tr>)}</tbody></table></div></div>
 <div style={{...styles.card,marginTop:20}}><h3>Recent stock movements</h3>{movements.slice(0,25).map(m=><div key={m.id} style={{padding:'10px 0',borderBottom:'1px solid #222'}}><strong style={{color:'#ff5500'}}>{m.action}</strong> — {m.asset_tag} {m.asset_name} · {m.from_location||'—'} → {m.to_location||'—'} · {m.to_user||'stock'}<div style={styles.muted}>{new Date(m.created_at).toLocaleString('en-GB')} · {m.performed_by}</div></div>)}{!movements.length&&<p style={styles.muted}>No stock movements yet.</p>}</div></div>
}
